import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.2)
mengetik('.....Mohon Tunggu.......')
mengetik('........................')
mengetik('15%.....................')
mengetik('..20%...................')
mengetik('....35%.................')
mengetik('......50%...............')
mengetik('........60%.............')
mengetik('..........75%...........')
mengetik('............85%.........')
mengetik('..............95%.......')
mengetik('................100%....')
mengetik('........................')
mengetik('...Meminta Akses Login...')
mengetik('.........................')
mengetik('.........................')
mengetik('.........................')
mengetik('..Meminta Akses Success..')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('...SYSTEM PROGRAM ACTIVE..')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('.......ERROR SYSTEM.......')
mengetik('..........................')
mengetik('Barang Siapa Yang Menggunakan Script Ini Dengan Merecode Scriptnya')
mengetik('Siap Siap Mukanya Di Upload Di Website Pemerintah Sekian Terima Kasih')
